apiVersion: v1
kind: Service
metadata:
  name: mysql-{{ .Release.Name }}-db-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type | default "ClusterIP"}}
  ports:
    - port: {{ .Values.service.port | default 3306 }}
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-{{ .Release.Name }}