kind: Secret
apiVersion: v1
metadata:
  name: mysql-{{ .Release.Name }}-dbsecret
  namespace: {{ .Release.Namespace}}
data:
  username: {{ print "root" | b64enc }}
  password: {{ .Values.auth.rootPassword | b64enc | quote | default "" }}
  dbuser: {{ print .Values.auth.username | b64enc | default "testuser"}}
  dbuserpass: {{ .Values.auth.password | b64enc | default "test123"}}