apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-{{ .Release.Name }}-dbinit
  namespace: {{ .Release.Namespace }}
data:
  host: mysql-{{ .Release.Name }}-db-svc.{{ .Release.Namespace }}.svc.cluster.local
  createdb.sql: |
    create database {{ .Values.auth.dbname | default .Release.Name }};
    grant all privileges on {{ .Values.auth.dbname | default .Release.Name }}.* to '{{ .Values.auth.username | default "testuser"}}'@'%';
    create database recordings;
    grant all privileges on recordings.* to 'root'@'%';
    grant all privileges on recordings.* to 'tectel'@'%';
    create table sakila.actor
    (
        ID    int auto_increment,
        FirstName  varchar(20) not null,
        LastName   varchar(20) not null,
        City        varchar(20)          default 'Tokyo' not null,
        LastUpdate timestamp   not null default current_timestamp on update current_timestamp,
        constraint actor_pk
            primary key (ID),
        constraint actor_pk2
            unique (FirstName, LastName)
    );
    create table recordings.album
    (
        ID int auto_increment not null,
        Title varchar(128) not null,
        Artist varchar(255) not null,
        Price decimal(5, 2) not null,
        LastUpdate timestamp not null default current_timestamp on update current_timestamp,
        primary key (id),
        unique key (title, artist, price)
    );
    insert into recordings.album
    (Title, Artist, Price)
    values
        ('Blue Train', 'John Coltrane', 56.99),
        ('Giant Steps', 'John Coltrane', 63.99),
        ('Jeru', 'Gerry Mulligan', 17.99),
        ('Sarah Vaughan', 'Sarah Vaughan', 34.98);