apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-crudapi
  labels:
    app: crudapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudapi
  template:
    metadata:
      labels:
        app: crudapi
    spec:
      serviceAccount: default
      containers:
        - name: server
          image: zawadimario/mysql-crud-api:v1.0
          ports:
          - containerPort: 8000
          env:
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "password"
          - name: DB_NAME
            value: "recordings"
          - name: DB_HOST
            value: "<change-here>"
          - name: DB_PORT
            value: "3306"
