apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-{{ .Release.Name }}-pv-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistentResources.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistentResources.storage }}